name: Run Docker Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t mrinal2100/docker-react1 -f Dockerfile.dev .

      - name: Run Tests inside Docker
        run: docker run -e CI=true mrinal2100/docker-react1 npm run test
